src/objects/Geocoding_Result__c.object
<CustomObject>
    <fields>
        <fullName>Confidence__c</fullName>
        <description>The confidence score returned from the geocoding service for this result</description>
        <inlineHelpText>The confidence score returned from the geocoding service for this result</inlineHelpText>
        <label>Confidence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Geocoded_Address__c</fullName>
        <description>The address the geocoder used for this result</description>
        <inlineHelpText>The address the geocoder used for this result</inlineHelpText>
        <label>Geocoded Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geocoding_Service__c</fullName>
        <description>The name of the service that provided this result</description>
        <inlineHelpText>The name of the service that provided this result</inlineHelpText>
        <label>Geocoding Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Record_Id__c</fullName>
        <description>The Id of the record whose address was requested for geocoding</description>
        <inlineHelpText>The Id of the record whose address was requested for geocoding</inlineHelpText>
        <label>Related Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Address__c</fullName>
        <description>The address sent to the service for geocoding.</description>
        <inlineHelpText>The address sent to the service for geocoding</inlineHelpText>
        <label>Requested Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>The score that determines which result is the winning result. May match confidence score from the geocoding service, or be adjusted by our own algorithm if the confidence is inaccurate.</description>
        <inlineHelpText>The score that determines which result is the winning result. May match confidence score from the geocoding service, or be adjusted by our own algorithm if the confidence is inaccurate.</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scoring_Method__c</fullName>
        <description>Describes the calculation used to determine this score</description>
        <inlineHelpText>Describes the calculation used to determine this score</inlineHelpText>
        <label>Scoring Method</label>
        <type>TextArea</type>
    </fields>
    <label>Geocoding Result</label>
    <nameField>
        <displayFormat>GEO-{00000}</displayFormat>
        <label>Geocoding Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geocoding Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Geocoding_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Class__c</fullName>
        <inlineHelpText>The Salesforce class responsible for calling the web service.</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Geocoding Settings</label>
</CustomObject>

src/classes/GEO_DemoGeocoder.cls
/**
* Copyright (c) 2017, Salesforce.org
* @author Laura Meerkatz
* @date 2017
* @description Geocoder implementation for demos. It's not hooked to a real service; It always returns the same coordinates.
*/
public with sharing class GEO_DemoGeocoder implements GEO_IGeocoder {

    private Geocoding_Settings__c settings;

    public GEO_DemoGeocoder() {
        settings = Geocoding_Settings__c.getInstance();
        if (settings == null) {
            throw new GEO_Geocoder.GeocodingException('Geocoding Settings have not been set.');
        } else if (settings.Class__c == null) {
            throw new GEO_Geocoder.GeocodingException('Required fields are missing from Geocoding Settings.');
        } else if (settings.Class__c != 'GEO_DemoGeocoder') {
            throw new GEO_Geocoder.GeocodingException(
                'GEO_DemoGeocoder can\'t be called directly when another service is set in Geocoding Settings.');
        }
    }

    /**
    * @description Provides the caller with the service name.
    * @return String The name of the geocoding service.
    */
    public String getServiceName(){
        return 'Demo Geocoding API';
    }

    /**
    * @description Tells the caller if the class supports batch geocoding.
    * @return Boolean
    */
    public Boolean supportsBatch(){
        return false;
    }

    /**
    * @description Returns geocoding results for a list of addresses.
    * @param addresses The list of addresses to be geocoded.
    * @return List<Geocoding_Result__c> The list of geocoding results.
    */
    public List<Geocoding_Result__c> geocodeAddresses(List<GEO_Address> addresses) {

        // since this doesn't support batch, remove all but the first record
        addresses = new List<GEO_Address>{ addresses[0] };

        List<Geocoding_Result__c> results = new List<Geocoding_Result__c>();

        results.add(new Geocoding_Result__c(
            Geocoding_Service__c = this.getServiceName(),
            Requested_Address__c = addresses[0].getQueryString(),
            Geocoded_Address__c = addresses[0].getQueryString(),
            Confidence__c = 10,
            Location__Latitude__s = 37.7831029,
            Location__Longitude__s = -122.4062475,
            Related_Record_Id__c = addresses[0].recordId,
            Score__c = 10,
            Scoring_Method__c = 'Value hard-coded for demo'
        ));

        return results;
    }


}