src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Include_in_Recommendations_Stored__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a copy of the Include in Recommendations formula field that is populated on a nightly schedule. Using this field instead of the formula field in queries improves performance significantly.</description>
        <inlineHelpText>This is a copy of the Include in Recommendations formula field that is populated on a nightly schedule. Using this field instead of the formula field in queries improves performance significantly.</inlineHelpText>
        <label>Include in Recommendations Stored</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Include_in_Recommendations__c</fullName>
        <formula>Session_Date__c &gt; NOW() &amp;&amp; 
(ISBLANK(Maximum_Attendees__c) || Maximum_Attendees__c &gt; Number_of_Attendees__c ) &amp;&amp;
!ISBLANK(Topics__c) &amp;&amp;
!CONTAINS(Name, &apos;private&apos;) &amp;&amp;
!CONTAINS(Name, &apos;executive track&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Criteria:
 - Session is in the future
 - Session isn&apos;t full
 - Session has a topic
 - Name doesn&apos;t include &apos;private&apos; or &apos;executive track&apos;</inlineHelpText>
        <label>Include in Recommendations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Levels__c</fullName>
        <inlineHelpText>Levels this session is appropriate for.</inlineHelpText>
        <label>Levels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Levels</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Maximum_Attendees__c</fullName>
        <label>Maximum Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <label>Number of Attendees</label>
        <summaryForeignKey>Attendee__c.Session__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Open_Slots__c</fullName>
        <formula>Maximum_Attendees__c - Number_of_Attendees__c</formula>
        <inlineHelpText>Formula: Maximum Attendees minus Number of Attendees</inlineHelpText>
        <label>Open Slots</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <inlineHelpText>Roles this session is appropriate for.</inlineHelpText>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Roles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_Date__c</fullName>
        <label>Session Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <inlineHelpText>Topics is this session covers.</inlineHelpText>
        <label>Topics</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topics</valueSetName>
        </valueSet>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Recommendations_SessionDemoData.cls
/**
* Copyright (c) 2017, Salesforce.org
* @author Laura Meerkatz
* @date 2017
* @description Query to pull a demo pool of sessions to use in recommendations. If this were a real implementation,
* you'd want a more generic query builder that would allow you to pass parameters in instead of hard-coding values
* like location.
*/

public with sharing class Recommendations_SessionDemoData {
    public static Location defaultLocation = Location.newInstance(37.7831029,-122.4040588);

    /********************** NOT GREAT **********************/

    // Criteria:
    // - Session is in the future
    // - Session isn't full
    // - Session has a topic
    // - Name doesn't include 'private' or 'executive track'
    public static List<Session__c> getSessionsEligibleForRecommendationsHardCoded() {
        return [
            SELECT Id, Name, Location__c, Location__Latitude__s, Location__Longitude__s,
                Number_of_Attendees__c, Maximum_Attendees__c, Session_Date__c
            FROM Session__c
            WHERE Session_Date__c >= TODAY AND
                (Maximum_Attendees__c = null OR
                    (Open_Slots__c != null AND Open_Slots__c > 0)) // <- this required creating a formula field
                    // because we can't compare two fields in a query
                AND Topics__c != null
                AND Name != '%private%'
                AND Name != '%executive track%'
            ORDER BY CreatedDate DESC
            LIMIT 200
        ];
    }

    /********************** BETTER **********************/

    // returns a list of eligible sessions
    // in a production scenario this should also be abstracted out
    public static List<Session__c> getSessionsEligibleForRecommendationsFormula() {
        return [
            SELECT Id, Name, Location__c, Location__Latitude__s, Location__Longitude__s,
                Number_of_Attendees__c, Maximum_Attendees__c, Session_Date__c
            FROM Session__c
            WHERE Include_in_Recommendations__c = true
            ORDER BY CreatedDate DESC
            LIMIT 200
        ];
    }

    /********************** BEST **********************/

    // returns a list of eligible sessions
    // in a production scenario this should also be abstracted out
    public static List<Session__c> getSessionsEligibleForRecommendationsStored() {
        return [
            SELECT Id, Name, Location__c, Location__Latitude__s, Location__Longitude__s,
                Number_of_Attendees__c, Maximum_Attendees__c, Session_Date__c,
                Topics__c, Roles__c, Levels__c
            FROM Session__c
            WHERE Include_in_Recommendations_Stored__c = true
            ORDER BY CreatedDate DESC
            LIMIT 200
        ];
    }


}